# fly.toml app configuration file generated for shots-game on 2025-11-21T12:00:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shots'
primary_region = 'iad'

[build]
  buildpacks = ["https://github.com/heroku/heroku-buildpack-static.git"]

[env]
  # No PORT needed for static

[[vm]]
  size = 'shared-cpu-1x'
