# fly.toml app configuration file generated for shots-game on 2025-11-21T12:00:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shots'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  SERVER_URL = "wss://shots.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  size = 'shared-cpu-1x'
